
-- ==========================================
-- ONESTARS MASTER RECOVERY SCRIPT
-- ==========================================

-- 1. Create Tables (if they don't exist)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE,
    full_name TEXT,
    avatar_url TEXT,
    is_admin BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'Active',
    country TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.market_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name TEXT NOT NULL,
    price_mmk BIGINT DEFAULT 0,
    description TEXT,
    platform TEXT,
    status TEXT DEFAULT 'available',
    image_url TEXT,
    profile_link TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.finance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name TEXT,
    amount_mmk BIGINT DEFAULT 0,
    status TEXT DEFAULT 'Pending',
    service_type TEXT,
    record_type TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Disable RLS (Row Level Security) - This ensures you can see everything
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.finance_records DISABLE ROW LEVEL SECURITY;

-- 3. Seed Sample Data (Only if empty)
INSERT INTO public.market_assets (asset_name, price_mmk, description, platform, status, image_url)
SELECT 'Facebook Monetized Page', 450000, 'High quality page with 10k followers', 'Facebook', 'available', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=800'
WHERE NOT EXISTS (SELECT 1 FROM public.market_assets LIMIT 1);

INSERT INTO public.market_assets (asset_name, price_mmk, description, platform, status, image_url)
SELECT 'TikTok Creator Account', 150000, 'US region account with creator fund', 'TikTok', 'available', 'https://images.unsplash.com/photo-1611605698335-8b1569810432?q=80&w=800'
WHERE NOT EXISTS (SELECT 1 FROM public.market_assets WHERE asset_name = 'TikTok Creator Account');

INSERT INTO public.finance_records (client_name, amount_mmk, status, service_type, record_type, notes)
SELECT 'Kyaw Kyaw', 50000, 'Paid', 'Page Setup', 'Income', 'Initial test record'
WHERE NOT EXISTS (SELECT 1 FROM public.finance_records LIMIT 1);

-- 4. Set Admin Access for your email
-- Replace with your actual ID if you know it, or this will update all matching emails
UPDATE public.profiles 
SET is_admin = true 
WHERE email = 'kyawkyawsmile12@gmail.com' OR email = 'admin@onestars.digital';

-- 5. Backfill profiles from auth.users
INSERT INTO public.profiles (id, email, is_admin)
SELECT id, email, (email = 'kyawkyawsmile12@gmail.com' OR email = 'admin@onestars.digital')
FROM auth.users
ON CONFLICT (id) DO UPDATE SET is_admin = EXCLUDED.is_admin;

-- 6. Refresh
NOTIFY pgrst, 'reload schema';
